#!/usr/bin/env python3
"""Generate XSD schemas from InputData specs.

Writes generated XSDs to developer_tools/XSDSchemas/generated by default.
"""
from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path
import xml.etree.ElementTree as ET
import importlib.util

REPO_ROOT = Path(__file__).resolve().parents[1]

sys.path.insert(0, str(REPO_ROOT))

from ravenframework.utils import InputData
InputData.SUPPRESS_INPUT_SPEC_WARNINGS = True

ENTITY_FACTORIES = {
    "Distributions": ("ravenframework.Distributions", "factory"),
    "Samplers": ("ravenframework.Samplers.Factory", "factory"),
    "Optimizers": ("ravenframework.Optimizers.Factory", "factory"),
    "Models": ("ravenframework.Models.Factory", "factory"),
    "Functions": ("ravenframework.Functions", "factory"),
    "Files": ("ravenframework.Files", "factory"),
    "Steps": ("ravenframework.Steps.Factory", "factory"),
    "Databases": ("ravenframework.Databases.Factory", "factory"),
    "DataObjects": ("ravenframework.DataObjects.Factory", "factory"),
    "OutStreams": ("ravenframework.OutStreams.Factory", "factory"),
    "Metrics": ("ravenframework.Metrics.Factory", "factory"),
}

_IMPORT_NAME_MAP = {
    "scikit-learn": "sklearn",
    "pyDOE3": "pyDOE3",
    "netcdf4": "netCDF4",
}


def _load_required_dependencies(dep_path: Path) -> list[str]:
    if not dep_path.exists():
        return []
    tree = ET.parse(str(dep_path))
    root = tree.getroot()
    main = root.find("main")
    if main is None:
        return []
    required = []
    for lib in main:
        optional = lib.attrib.get("optional", "false").lower() == "true"
        if optional:
            continue
        if lib.text and lib.text.strip().lower() == "remove":
            continue
        required.append(lib.tag)
    return required


def _is_python_package(name: str) -> bool:
    non_python = {"python", "hdf5", "swig", "nomkl", "cmake", "glpk", "ipopt", "mamba"}
    return name.lower() not in non_python


def _check_required_dependencies(dep_path: Path, strict: bool = False) -> None:
    required = _load_required_dependencies(dep_path)
    # Only enforce deps needed for factory imports unless strict is requested.
    if not strict:
        required = [dep for dep in required if dep in {"xarray", "pyDOE3", "h5py", "netcdf4", "scikit-learn", "pandas", "numpy", "scipy"}]
    missing = []
    for dep in required:
        if not _is_python_package(dep):
            continue
        import_name = _IMPORT_NAME_MAP.get(dep, dep)
        if importlib.util.find_spec(import_name) is None:
            missing.append(dep)
    if missing:
        scope = "strict" if strict else "minimal"
        raise RuntimeError(
            f"Missing required Python dependencies ({scope} preflight): "
            + ", ".join(sorted(missing))
        )


def _load_factory(module_path: str, attr: str):
    module = importlib.import_module(module_path)
    return getattr(module, attr)


def _build_container(entity: str, factory) -> InputData.ParameterInput:
    container = InputData.parameterInputFactory(entity)
    for type_name in sorted(factory.knownTypes()):
        try:
            cls = factory.returnClass(type_name)
            spec = cls.getInputSpecification()
            spec.name = type_name
            container.addSub(spec)
        except Exception as exc:
            print(f"WARN: skipping {entity}:{type_name} ({exc})")
    return container


def _write_xsd(out_dir: Path, entity: str, container: InputData.ParameterInput):
    out_dir.mkdir(parents=True, exist_ok=True)
    xsd_root = InputData.createXSD(container)
    tree = ET.ElementTree(xsd_root)
    out_path = out_dir / f"{entity}.xsd"
    tree.write(out_path, encoding="utf-8", xml_declaration=True)
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(REPO_ROOT / "developer_tools" / "XSDSchemas" / "generated"))
    parser.add_argument("--skip-preflight", action="store_true", help="Skip dependencies.xml preflight check")
    parser.add_argument("--strict-preflight", action="store_true", help="Require all non-optional deps from dependencies.xml")
    args = parser.parse_args()

    out_dir = Path(args.out)
    if not args.skip_preflight:
        _check_required_dependencies(REPO_ROOT / "dependencies.xml", strict=args.strict_preflight)
    for entity, (module_path, attr) in ENTITY_FACTORIES.items():
        try:
            factory = _load_factory(module_path, attr)
        except Exception as exc:
            print(f"WARN: skipping {entity} (failed to import factory: {exc})")
            continue
        container = _build_container(entity, factory)
        out_path = _write_xsd(out_dir, entity, container)
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
