# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _distribution1D
else:
    import _distribution1D

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _distribution1D.delete_SwigPyIterator

    def value(self):
        return _distribution1D.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _distribution1D.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _distribution1D.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _distribution1D.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _distribution1D.SwigPyIterator_equal(self, x)

    def copy(self):
        return _distribution1D.SwigPyIterator_copy(self)

    def next(self):
        return _distribution1D.SwigPyIterator_next(self)

    def __next__(self):
        return _distribution1D.SwigPyIterator___next__(self)

    def previous(self):
        return _distribution1D.SwigPyIterator_previous(self)

    def advance(self, n):
        return _distribution1D.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _distribution1D.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _distribution1D.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _distribution1D.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _distribution1D.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _distribution1D.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _distribution1D.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _distribution1D:
_distribution1D.SwigPyIterator_swigregister(SwigPyIterator)
MULTIPLICATIVE = _distribution1D.MULTIPLICATIVE
SUM = _distribution1D.SUM
class BasicDistribution(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _distribution1D.delete_BasicDistribution

    def getVariable(self, variable_name):
        return _distribution1D.BasicDistribution_getVariable(self, variable_name)

    def getVariableVector(self, variable_name):
        return _distribution1D.BasicDistribution_getVariableVector(self, variable_name)

    def updateVariable(self, variable_name, new_value):
        return _distribution1D.BasicDistribution_updateVariable(self, variable_name, new_value)

    def getRandom(self, x):
        return _distribution1D.BasicDistribution_getRandom(self, x)

    def pdf(self, x):
        return _distribution1D.BasicDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicDistribution_inverseCdf(self, x)

    def untrPdf(self, x):
        return _distribution1D.BasicDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicDistribution_untrCdf(self, x)

    def untrCdfComplement(self, x):
        return _distribution1D.BasicDistribution_untrCdfComplement(self, x)

    def untrInverseCdf(self, x):
        return _distribution1D.BasicDistribution_untrInverseCdf(self, x)

    def untrMean(self):
        return _distribution1D.BasicDistribution_untrMean(self)

    def untrStdDev(self):
        return _distribution1D.BasicDistribution_untrStdDev(self)

    def untrMedian(self):
        return _distribution1D.BasicDistribution_untrMedian(self)

    def untrMode(self):
        return _distribution1D.BasicDistribution_untrMode(self)

    def untrHazard(self, x):
        return _distribution1D.BasicDistribution_untrHazard(self, x)

    def returnDimensionality(self):
        return _distribution1D.BasicDistribution_returnDimensionality(self)

    def getType(self):
        return _distribution1D.BasicDistribution_getType(self)

    def getSeed(self):
        return _distribution1D.BasicDistribution_getSeed(self)

    def getVariableNames(self):
        return _distribution1D.BasicDistribution_getVariableNames(self)

# Register BasicDistribution in _distribution1D:
_distribution1D.BasicDistribution_swigregister(BasicDistribution)
cvar = _distribution1D.cvar
_defaultSeed = cvar._defaultSeed

class DistributionContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def instance():
        return _distribution1D.DistributionContainer_instance()

    def addDistributionInContainer(self, type, name, dist):
        return _distribution1D.DistributionContainer_addDistributionInContainer(self, type, name, dist)

    def addDistributionInContainerND(self, type, name, dist):
        return _distribution1D.DistributionContainer_addDistributionInContainerND(self, type, name, dist)

    def seedRandom(self, seed):
        return _distribution1D.DistributionContainer_seedRandom(self, seed)

    def isEmpty(self):
        return _distribution1D.DistributionContainer_isEmpty(self)

    def getType(self, *args):
        return _distribution1D.DistributionContainer_getType(self, *args)

    def getVariable(self, *args):
        return _distribution1D.DistributionContainer_getVariable(self, *args)

    def updateVariable(self, *args):
        return _distribution1D.DistributionContainer_updateVariable(self, *args)

    def getDistributionVariableNames(self, dist_alias):
        return _distribution1D.DistributionContainer_getDistributionVariableNames(self, dist_alias)

    def getDistributionNames(self):
        return _distribution1D.DistributionContainer_getDistributionNames(self)

    def pdf(self, *args):
        return _distribution1D.DistributionContainer_pdf(self, *args)

    def cdf(self, *args):
        return _distribution1D.DistributionContainer_cdf(self, *args)

    def getDistributionRandom(self, *args):
        return _distribution1D.DistributionContainer_getDistributionRandom(self, *args)

    def inverseCdf(self, *args):
        return _distribution1D.DistributionContainer_inverseCdf(self, *args)

    def random(self):
        return _distribution1D.DistributionContainer_random(self)

    def checkCdf(self, *args):
        return _distribution1D.DistributionContainer_checkCdf(self, *args)

    def getTriggerStatus(self, *args):
        return _distribution1D.DistributionContainer_getTriggerStatus(self, *args)

    def lastDistributionTriggered(self):
        return _distribution1D.DistributionContainer_lastDistributionTriggered(self)

    def atLeastADistTriggered(self):
        return _distribution1D.DistributionContainer_atLeastADistTriggered(self)

    def returnDimensionality(self, *args):
        return _distribution1D.DistributionContainer_returnDimensionality(self, *args)

# Register DistributionContainer in _distribution1D:
_distribution1D.DistributionContainer_swigregister(DistributionContainer)

def strToStringP(s):
    return _distribution1D.strToStringP(s)

def stringPToSt(s):
    return _distribution1D.stringPToSt(s)

def freeStringP(s):
    return _distribution1D.freeStringP(s)
class BasicTruncatedDistribution(BasicDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicTruncatedDistribution_swiginit(self, _distribution1D.new_BasicTruncatedDistribution(*args))

    def pdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_inverseCdf(self, x)

    def untrPdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_untrCdf(self, x)

    def untrCdfComplement(self, x):
        return _distribution1D.BasicTruncatedDistribution_untrCdfComplement(self, x)

    def untrInverseCdf(self, x):
        return _distribution1D.BasicTruncatedDistribution_untrInverseCdf(self, x)

    def untrMean(self):
        return _distribution1D.BasicTruncatedDistribution_untrMean(self)

    def untrStdDev(self):
        return _distribution1D.BasicTruncatedDistribution_untrStdDev(self)

    def untrMedian(self):
        return _distribution1D.BasicTruncatedDistribution_untrMedian(self)

    def untrMode(self):
        return _distribution1D.BasicTruncatedDistribution_untrMode(self)

    def untrHazard(self, x):
        return _distribution1D.BasicTruncatedDistribution_untrHazard(self, x)
    __swig_destroy__ = _distribution1D.delete_BasicTruncatedDistribution

# Register BasicTruncatedDistribution in _distribution1D:
_distribution1D.BasicTruncatedDistribution_swigregister(BasicTruncatedDistribution)
class BasicDiscreteDistribution(BasicDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def pdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_inverseCdf(self, x)

    def untrPdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_untrCdf(self, x)

    def untrCdfComplement(self, x):
        return _distribution1D.BasicDiscreteDistribution_untrCdfComplement(self, x)

    def untrInverseCdf(self, x):
        return _distribution1D.BasicDiscreteDistribution_untrInverseCdf(self, x)

    def untrMean(self):
        return _distribution1D.BasicDiscreteDistribution_untrMean(self)

    def untrStdDev(self):
        return _distribution1D.BasicDiscreteDistribution_untrStdDev(self)

    def untrMedian(self):
        return _distribution1D.BasicDiscreteDistribution_untrMedian(self)

    def untrMode(self):
        return _distribution1D.BasicDiscreteDistribution_untrMode(self)

    def untrHazard(self, x):
        return _distribution1D.BasicDiscreteDistribution_untrHazard(self, x)

    def __init__(self):
        _distribution1D.BasicDiscreteDistribution_swiginit(self, _distribution1D.new_BasicDiscreteDistribution())
    __swig_destroy__ = _distribution1D.delete_BasicDiscreteDistribution

# Register BasicDiscreteDistribution in _distribution1D:
_distribution1D.BasicDiscreteDistribution_swigregister(BasicDiscreteDistribution)
class BasicUniformDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, x_min, x_max):
        _distribution1D.BasicUniformDistribution_swiginit(self, _distribution1D.new_BasicUniformDistribution(x_min, x_max))
    __swig_destroy__ = _distribution1D.delete_BasicUniformDistribution

    def pdf(self, x):
        return _distribution1D.BasicUniformDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicUniformDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicUniformDistribution_inverseCdf(self, x)

# Register BasicUniformDistribution in _distribution1D:
_distribution1D.BasicUniformDistribution_swigregister(BasicUniformDistribution)
class BasicNormalDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicNormalDistribution_swiginit(self, _distribution1D.new_BasicNormalDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicNormalDistribution

    def inverseCdf(self, x):
        return _distribution1D.BasicNormalDistribution_inverseCdf(self, x)

# Register BasicNormalDistribution in _distribution1D:
_distribution1D.BasicNormalDistribution_swigregister(BasicNormalDistribution)
class BasicLogNormalDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicLogNormalDistribution_swiginit(self, _distribution1D.new_BasicLogNormalDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicLogNormalDistribution

    def inverseCdf(self, x):
        return _distribution1D.BasicLogNormalDistribution_inverseCdf(self, x)

    def untrPdf(self, x):
        return _distribution1D.BasicLogNormalDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicLogNormalDistribution_untrCdf(self, x)

# Register BasicLogNormalDistribution in _distribution1D:
_distribution1D.BasicLogNormalDistribution_swigregister(BasicLogNormalDistribution)
class BasicLogisticDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicLogisticDistribution_swiginit(self, _distribution1D.new_BasicLogisticDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicLogisticDistribution

# Register BasicLogisticDistribution in _distribution1D:
_distribution1D.BasicLogisticDistribution_swigregister(BasicLogisticDistribution)
class BasicLaplaceDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, location, scale, x_min, x_max):
        _distribution1D.BasicLaplaceDistribution_swiginit(self, _distribution1D.new_BasicLaplaceDistribution(location, scale, x_min, x_max))
    __swig_destroy__ = _distribution1D.delete_BasicLaplaceDistribution

# Register BasicLaplaceDistribution in _distribution1D:
_distribution1D.BasicLaplaceDistribution_swigregister(BasicLaplaceDistribution)
class BasicTriangularDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, x_peak, lower_bound, upper_bound):
        _distribution1D.BasicTriangularDistribution_swiginit(self, _distribution1D.new_BasicTriangularDistribution(x_peak, lower_bound, upper_bound))
    __swig_destroy__ = _distribution1D.delete_BasicTriangularDistribution

# Register BasicTriangularDistribution in _distribution1D:
_distribution1D.BasicTriangularDistribution_swigregister(BasicTriangularDistribution)
class BasicExponentialDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicExponentialDistribution_swiginit(self, _distribution1D.new_BasicExponentialDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicExponentialDistribution

    def untrPdf(self, x):
        return _distribution1D.BasicExponentialDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicExponentialDistribution_untrCdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicExponentialDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicExponentialDistribution_inverseCdf(self, x)

# Register BasicExponentialDistribution in _distribution1D:
_distribution1D.BasicExponentialDistribution_swigregister(BasicExponentialDistribution)
class BasicWeibullDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicWeibullDistribution_swiginit(self, _distribution1D.new_BasicWeibullDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicWeibullDistribution

    def untrPdf(self, x):
        return _distribution1D.BasicWeibullDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicWeibullDistribution_untrCdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicWeibullDistribution_inverseCdf(self, x)

# Register BasicWeibullDistribution in _distribution1D:
_distribution1D.BasicWeibullDistribution_swigregister(BasicWeibullDistribution)
class BasicGammaDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicGammaDistribution_swiginit(self, _distribution1D.new_BasicGammaDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicGammaDistribution

    def untrPdf(self, x):
        return _distribution1D.BasicGammaDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicGammaDistribution_untrCdf(self, x)

    def untrInverseCdf(self, x):
        return _distribution1D.BasicGammaDistribution_untrInverseCdf(self, x)

# Register BasicGammaDistribution in _distribution1D:
_distribution1D.BasicGammaDistribution_swigregister(BasicGammaDistribution)
class BasicBetaDistribution(BasicTruncatedDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicBetaDistribution_swiginit(self, _distribution1D.new_BasicBetaDistribution(*args))
    __swig_destroy__ = _distribution1D.delete_BasicBetaDistribution

    def pdf(self, x):
        return _distribution1D.BasicBetaDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicBetaDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicBetaDistribution_inverseCdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicBetaDistribution_untrCdf(self, x)

    def untrPdf(self, x):
        return _distribution1D.BasicBetaDistribution_untrPdf(self, x)

# Register BasicBetaDistribution in _distribution1D:
_distribution1D.BasicBetaDistribution_swigregister(BasicBetaDistribution)
class BasicPoissonDistribution(BasicDiscreteDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, mu):
        _distribution1D.BasicPoissonDistribution_swiginit(self, _distribution1D.new_BasicPoissonDistribution(mu))
    __swig_destroy__ = _distribution1D.delete_BasicPoissonDistribution

    def pdf(self, x):
        return _distribution1D.BasicPoissonDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicPoissonDistribution_cdf(self, x)

    def inverseCdf(self, x):
        return _distribution1D.BasicPoissonDistribution_inverseCdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicPoissonDistribution_untrCdf(self, x)

# Register BasicPoissonDistribution in _distribution1D:
_distribution1D.BasicPoissonDistribution_swigregister(BasicPoissonDistribution)
class BasicBinomialDistribution(BasicDiscreteDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n, p):
        _distribution1D.BasicBinomialDistribution_swiginit(self, _distribution1D.new_BasicBinomialDistribution(n, p))
    __swig_destroy__ = _distribution1D.delete_BasicBinomialDistribution

    def untrCdf(self, x):
        return _distribution1D.BasicBinomialDistribution_untrCdf(self, x)

# Register BasicBinomialDistribution in _distribution1D:
_distribution1D.BasicBinomialDistribution_swigregister(BasicBinomialDistribution)
class BasicBernoulliDistribution(BasicDiscreteDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, p):
        _distribution1D.BasicBernoulliDistribution_swiginit(self, _distribution1D.new_BasicBernoulliDistribution(p))
    __swig_destroy__ = _distribution1D.delete_BasicBernoulliDistribution

# Register BasicBernoulliDistribution in _distribution1D:
_distribution1D.BasicBernoulliDistribution_swigregister(BasicBernoulliDistribution)
class BasicGeometricDistribution(BasicDiscreteDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, p):
        _distribution1D.BasicGeometricDistribution_swiginit(self, _distribution1D.new_BasicGeometricDistribution(p))
    __swig_destroy__ = _distribution1D.delete_BasicGeometricDistribution

# Register BasicGeometricDistribution in _distribution1D:
_distribution1D.BasicGeometricDistribution_swigregister(BasicGeometricDistribution)
class BasicConstantDistribution(BasicDistribution):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value):
        _distribution1D.BasicConstantDistribution_swiginit(self, _distribution1D.new_BasicConstantDistribution(value))
    __swig_destroy__ = _distribution1D.delete_BasicConstantDistribution

    def pdf(self, x):
        return _distribution1D.BasicConstantDistribution_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicConstantDistribution_cdf(self, x)

    def inverseCdf(self, arg2):
        return _distribution1D.BasicConstantDistribution_inverseCdf(self, arg2)

    def untrPdf(self, x):
        return _distribution1D.BasicConstantDistribution_untrPdf(self, x)

    def untrCdf(self, x):
        return _distribution1D.BasicConstantDistribution_untrCdf(self, x)

    def untrCdfComplement(self, x):
        return _distribution1D.BasicConstantDistribution_untrCdfComplement(self, x)

    def untrInverseCdf(self, arg2):
        return _distribution1D.BasicConstantDistribution_untrInverseCdf(self, arg2)

    def untrMean(self):
        return _distribution1D.BasicConstantDistribution_untrMean(self)

    def untrStdDev(self):
        return _distribution1D.BasicConstantDistribution_untrStdDev(self)

    def untrMedian(self):
        return _distribution1D.BasicConstantDistribution_untrMedian(self)

    def untrMode(self):
        return _distribution1D.BasicConstantDistribution_untrMode(self)

    def untrHazard(self, x):
        return _distribution1D.BasicConstantDistribution_untrHazard(self, x)

# Register BasicConstantDistribution in _distribution1D:
_distribution1D.BasicConstantDistribution_swigregister(BasicConstantDistribution)

def checkUpperBound(upper_bound, values):
    return _distribution1D.checkUpperBound(upper_bound, values)

def checkLowerBound(lower_bound, values):
    return _distribution1D.checkLowerBound(lower_bound, values)

def intToBinary(value, size):
    return _distribution1D.intToBinary(value, size)
class NDInterpolation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def interpolateAt(self, point_coordinate):
        return _distribution1D.NDInterpolation_interpolateAt(self, point_coordinate)

    def getGradientAt(self, point_coordinate):
        return _distribution1D.NDInterpolation_getGradientAt(self, point_coordinate)

    def fit(self, coordinates, values):
        return _distribution1D.NDInterpolation_fit(self, coordinates, values)

    def ndInverseFunctionGrid(self, f, g):
        return _distribution1D.NDInterpolation_ndInverseFunctionGrid(self, f, g)

    def averageCellValue(self, center, dx):
        return _distribution1D.NDInterpolation_averageCellValue(self, center, dx)

    def updateRNGParameters(self, tolerance, initial_divisions):
        return _distribution1D.NDInterpolation_updateRNGParameters(self, tolerance, initial_divisions)

    def ndDerivative(self, coordinate):
        return _distribution1D.NDInterpolation_ndDerivative(self, coordinate)

    def returnDimensionality(self):
        return _distribution1D.NDInterpolation_returnDimensionality(self)

    def returnUpperBound(self, dimension):
        return _distribution1D.NDInterpolation_returnUpperBound(self, dimension)

    def returnLowerBound(self, dimension):
        return _distribution1D.NDInterpolation_returnLowerBound(self, dimension)

    def __init__(self):
        _distribution1D.NDInterpolation_swiginit(self, _distribution1D.new_NDInterpolation())
    __swig_destroy__ = _distribution1D.delete_NDInterpolation

# Register NDInterpolation in _distribution1D:
_distribution1D.NDInterpolation_swigregister(NDInterpolation)
class NDSpline(NDInterpolation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def interpolateAt(self, point_coordinate):
        return _distribution1D.NDSpline_interpolateAt(self, point_coordinate)

    def getGradientAt(self, point_coordinate):
        return _distribution1D.NDSpline_getGradientAt(self, point_coordinate)

    def integralSpline(self, point_coordinate):
        return _distribution1D.NDSpline_integralSpline(self, point_coordinate)

    def splineCartesianMarginalIntegration(self, coordinate, marginal_variable):
        return _distribution1D.NDSpline_splineCartesianMarginalIntegration(self, coordinate, marginal_variable)

    def splineCartesianInverseMarginal(self, cdf, marginal_variable, precision):
        return _distribution1D.NDSpline_splineCartesianInverseMarginal(self, cdf, marginal_variable, precision)

    def fit(self, coordinates, values):
        return _distribution1D.NDSpline_fit(self, coordinates, values)

    def ndSplineInit(self, discretizations, values, alpha, beta):
        return _distribution1D.NDSpline_ndSplineInit(self, discretizations, values, alpha, beta)

    def getDiscretizations(self, vector):
        return _distribution1D.NDSpline_getDiscretizations(self, vector)

    def printFunction(self):
        return _distribution1D.NDSpline_printFunction(self)

    def __init__(self, *args):
        _distribution1D.NDSpline_swiginit(self, _distribution1D.new_NDSpline(*args))
    __swig_destroy__ = _distribution1D.delete_NDSpline

    def checkUB(self, upper_bound):
        return _distribution1D.NDSpline_checkUB(self, upper_bound)

    def checkLB(self, lower_bound):
        return _distribution1D.NDSpline_checkLB(self, lower_bound)

    def checkBoundaries(self, point):
        return _distribution1D.NDSpline_checkBoundaries(self, point)

    def getH(self, dim):
        return _distribution1D.NDSpline_getH(self, dim)

# Register NDSpline in _distribution1D:
_distribution1D.NDSpline_swigregister(NDSpline)
class InverseDistanceWeighting(NDInterpolation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def interpolateAt(self, point_coordinate):
        return _distribution1D.InverseDistanceWeighting_interpolateAt(self, point_coordinate)

    def getGradientAt(self, point_coordinate):
        return _distribution1D.InverseDistanceWeighting_getGradientAt(self, point_coordinate)

    def fit(self, coordinates, values):
        return _distribution1D.InverseDistanceWeighting_fit(self, coordinates, values)

    def __init__(self, *args):
        _distribution1D.InverseDistanceWeighting_swiginit(self, _distribution1D.new_InverseDistanceWeighting(*args))
    __swig_destroy__ = _distribution1D.delete_InverseDistanceWeighting

    def checkUB(self, upper_bound):
        return _distribution1D.InverseDistanceWeighting_checkUB(self, upper_bound)

    def checkLB(self, lower_bound):
        return _distribution1D.InverseDistanceWeighting_checkLB(self, lower_bound)

    def getCellPoint0(self):
        return _distribution1D.InverseDistanceWeighting_getCellPoint0(self)

    def getCellDxs(self):
        return _distribution1D.InverseDistanceWeighting_getCellDxs(self)

# Register InverseDistanceWeighting in _distribution1D:
_distribution1D.InverseDistanceWeighting_swigregister(InverseDistanceWeighting)
class MicroSphere(NDInterpolation):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def interpolateAt(self, point_coordinate):
        return _distribution1D.MicroSphere_interpolateAt(self, point_coordinate)

    def getGradientAt(self, point_coordinate):
        return _distribution1D.MicroSphere_getGradientAt(self, point_coordinate)

    def fit(self, coordinates, values):
        return _distribution1D.MicroSphere_fit(self, coordinates, values)

    def __init__(self, *args):
        _distribution1D.MicroSphere_swiginit(self, _distribution1D.new_MicroSphere(*args))
    __swig_destroy__ = _distribution1D.delete_MicroSphere

# Register MicroSphere in _distribution1D:
_distribution1D.MicroSphere_swigregister(MicroSphere)
PDF = _distribution1D.PDF
CDF = _distribution1D.CDF
class BasicDistributionND(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _distribution1D.delete_BasicDistributionND

    def getVariable(self, variable_name):
        return _distribution1D.BasicDistributionND_getVariable(self, variable_name)

    def updateVariable(self, variable_name, new_value):
        return _distribution1D.BasicDistributionND_updateVariable(self, variable_name, new_value)

    def pdf(self, x):
        return _distribution1D.BasicDistributionND_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicDistributionND_cdf(self, x)

    def inverseCdf(self, f, g):
        return _distribution1D.BasicDistributionND_inverseCdf(self, f, g)

    def inverseMarginal(self, f, dimension):
        return _distribution1D.BasicDistributionND_inverseMarginal(self, f, dimension)

    def returnDimensionality(self):
        return _distribution1D.BasicDistributionND_returnDimensionality(self)

    def cellIntegral(self, center, dx):
        return _distribution1D.BasicDistributionND_cellIntegral(self, center, dx)

    def returnUpperBound(self, dimension):
        return _distribution1D.BasicDistributionND_returnUpperBound(self, dimension)

    def returnLowerBound(self, dimension):
        return _distribution1D.BasicDistributionND_returnLowerBound(self, dimension)

    def getType(self):
        return _distribution1D.BasicDistributionND_getType(self)

    def oneDtoNDconverter(self, one_d_coordinate, indexes):
        return _distribution1D.BasicDistributionND_oneDtoNDconverter(self, one_d_coordinate, indexes)

# Register BasicDistributionND in _distribution1D:
_distribution1D.BasicDistributionND_swigregister(BasicDistributionND)
class BasicMultiDimensionalCartesianSpline(BasicDistributionND):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def basicMultiDimensionalCartesianSplineInit(self):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_basicMultiDimensionalCartesianSplineInit(self)

    def __init__(self, *args):
        _distribution1D.BasicMultiDimensionalCartesianSpline_swiginit(self, _distribution1D.new_BasicMultiDimensionalCartesianSpline(*args))
    __swig_destroy__ = _distribution1D.delete_BasicMultiDimensionalCartesianSpline

    def pdf(self, x):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_cdf(self, x)

    def inverseCdf(self, f, g):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_inverseCdf(self, f, g)

    def inverseMarginal(self, f, dimension):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_inverseMarginal(self, f, dimension)

    def returnDimensionality(self):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_returnDimensionality(self)

    def updateRNGparameter(self, tolerance, initial_divisions):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_updateRNGparameter(self, tolerance, initial_divisions)

    def marginal(self, x, dimension):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_marginal(self, x, dimension)

    def returnUpperBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_returnUpperBound(self, dimension)

    def returnLowerBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalCartesianSpline_returnLowerBound(self, dimension)

# Register BasicMultiDimensionalCartesianSpline in _distribution1D:
_distribution1D.BasicMultiDimensionalCartesianSpline_swigregister(BasicMultiDimensionalCartesianSpline)
class BasicMultiDimensionalInverseWeight(BasicDistributionND):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicMultiDimensionalInverseWeight_swiginit(self, _distribution1D.new_BasicMultiDimensionalInverseWeight(*args))

    def basicMultiDimensionalInverseWeightInit(self):
        return _distribution1D.BasicMultiDimensionalInverseWeight_basicMultiDimensionalInverseWeightInit(self)
    __swig_destroy__ = _distribution1D.delete_BasicMultiDimensionalInverseWeight

    def pdf(self, x):
        return _distribution1D.BasicMultiDimensionalInverseWeight_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicMultiDimensionalInverseWeight_cdf(self, x)

    def updateRNGparameter(self, tolerance, initial_divisions):
        return _distribution1D.BasicMultiDimensionalInverseWeight_updateRNGparameter(self, tolerance, initial_divisions)

    def inverseCdf(self, f, g):
        return _distribution1D.BasicMultiDimensionalInverseWeight_inverseCdf(self, f, g)

    def inverseMarginal(self, f, dimension):
        return _distribution1D.BasicMultiDimensionalInverseWeight_inverseMarginal(self, f, dimension)

    def marginal(self, x, dimension):
        return _distribution1D.BasicMultiDimensionalInverseWeight_marginal(self, x, dimension)

    def returnDimensionality(self):
        return _distribution1D.BasicMultiDimensionalInverseWeight_returnDimensionality(self)

    def returnUpperBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalInverseWeight_returnUpperBound(self, dimension)

    def returnLowerBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalInverseWeight_returnLowerBound(self, dimension)

# Register BasicMultiDimensionalInverseWeight in _distribution1D:
_distribution1D.BasicMultiDimensionalInverseWeight_swigregister(BasicMultiDimensionalInverseWeight)
class BasicMultiDimensionalScatteredMS(BasicDistributionND):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicMultiDimensionalScatteredMS_swiginit(self, _distribution1D.new_BasicMultiDimensionalScatteredMS(*args))
    __swig_destroy__ = _distribution1D.delete_BasicMultiDimensionalScatteredMS

    def pdf(self, x):
        return _distribution1D.BasicMultiDimensionalScatteredMS_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicMultiDimensionalScatteredMS_cdf(self, x)

    def inverseCdf(self, f, g):
        return _distribution1D.BasicMultiDimensionalScatteredMS_inverseCdf(self, f, g)

    def inverseMarginal(self, arg2, arg3):
        return _distribution1D.BasicMultiDimensionalScatteredMS_inverseMarginal(self, arg2, arg3)

    def returnDimensionality(self):
        return _distribution1D.BasicMultiDimensionalScatteredMS_returnDimensionality(self)

    def returnLowerBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalScatteredMS_returnLowerBound(self, dimension)

    def returnUpperBound(self, dimension):
        return _distribution1D.BasicMultiDimensionalScatteredMS_returnUpperBound(self, dimension)

# Register BasicMultiDimensionalScatteredMS in _distribution1D:
_distribution1D.BasicMultiDimensionalScatteredMS_swigregister(BasicMultiDimensionalScatteredMS)
class BasicMultivariateNormal(BasicDistributionND):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _distribution1D.BasicMultivariateNormal_swiginit(self, _distribution1D.new_BasicMultivariateNormal(*args))

    def basicMultivariateNormalInit(self, rows, columns, cov_matrix, mu):
        return _distribution1D.BasicMultivariateNormal_basicMultivariateNormalInit(self, rows, columns, cov_matrix, mu)
    __swig_destroy__ = _distribution1D.delete_BasicMultivariateNormal

    def pdf(self, x):
        return _distribution1D.BasicMultivariateNormal_pdf(self, x)

    def cdf(self, x):
        return _distribution1D.BasicMultivariateNormal_cdf(self, x)

    def inverseCdf(self, f, g):
        return _distribution1D.BasicMultivariateNormal_inverseCdf(self, f, g)

    def inverseMarginal(self, f, dimension):
        return _distribution1D.BasicMultivariateNormal_inverseMarginal(self, f, dimension)

    def updateRNGparameter(self, tolerance, initial_divisions):
        return _distribution1D.BasicMultivariateNormal_updateRNGparameter(self, tolerance, initial_divisions)

    def marginal(self, x, dimension):
        return _distribution1D.BasicMultivariateNormal_marginal(self, x, dimension)

    def returnDimensionality(self):
        return _distribution1D.BasicMultivariateNormal_returnDimensionality(self)

    def phi(self, x):
        return _distribution1D.BasicMultivariateNormal_phi(self, x)

    def phiInv(self, x):
        return _distribution1D.BasicMultivariateNormal_phiInv(self, x)

    def cholesky(self, A, n):
        return _distribution1D.BasicMultivariateNormal_cholesky(self, A, n)

    def choleskyDecomposition(self, matrix):
        return _distribution1D.BasicMultivariateNormal_choleskyDecomposition(self, matrix)

    def showMatrix(self, A, n):
        return _distribution1D.BasicMultivariateNormal_showMatrix(self, A, n)

    def getSingularValues(self, *args):
        return _distribution1D.BasicMultivariateNormal_getSingularValues(self, *args)

    def getLeftSingularVectors(self, *args):
        return _distribution1D.BasicMultivariateNormal_getLeftSingularVectors(self, *args)

    def getRightSingularVectors(self, *args):
        return _distribution1D.BasicMultivariateNormal_getRightSingularVectors(self, *args)

    def getLeftSingularVectorsDimensions(self, *args):
        return _distribution1D.BasicMultivariateNormal_getLeftSingularVectorsDimensions(self, *args)

    def getRightSingularVectorsDimensions(self, *args):
        return _distribution1D.BasicMultivariateNormal_getRightSingularVectorsDimensions(self, *args)

    def getTransformationMatrix(self, *args):
        return _distribution1D.BasicMultivariateNormal_getTransformationMatrix(self, *args)

    def getTransformationMatrixDimensions(self, *args):
        return _distribution1D.BasicMultivariateNormal_getTransformationMatrixDimensions(self, *args)

    def getInverseTransformationMatrix(self, *args):
        return _distribution1D.BasicMultivariateNormal_getInverseTransformationMatrix(self, *args)

    def getInverseTransformationMatrixDimensions(self, *args):
        return _distribution1D.BasicMultivariateNormal_getInverseTransformationMatrixDimensions(self, *args)

    def getSingularValuesDimension(self, *args):
        return _distribution1D.BasicMultivariateNormal_getSingularValuesDimension(self, *args)

    def coordinateInTransformedSpace(self, rank):
        return _distribution1D.BasicMultivariateNormal_coordinateInTransformedSpace(self, rank)

    def coordinateInverseTransformed(self, *args):
        return _distribution1D.BasicMultivariateNormal_coordinateInverseTransformed(self, *args)

    def cellProbabilityWeight(self, center, dx):
        return _distribution1D.BasicMultivariateNormal_cellProbabilityWeight(self, center, dx)

    def inverseMarginalForPCA(self, f):
        return _distribution1D.BasicMultivariateNormal_inverseMarginalForPCA(self, f)

    def marginalCdfForPCA(self, x):
        return _distribution1D.BasicMultivariateNormal_marginalCdfForPCA(self, x)

    def computeSVD(self, *args):
        return _distribution1D.BasicMultivariateNormal_computeSVD(self, *args)

    def pdfInTransformedSpace(self, x):
        return _distribution1D.BasicMultivariateNormal_pdfInTransformedSpace(self, x)

    def returnLowerBound(self, dimension):
        return _distribution1D.BasicMultivariateNormal_returnLowerBound(self, dimension)

    def returnUpperBound(self, dimension):
        return _distribution1D.BasicMultivariateNormal_returnUpperBound(self, dimension)

# Register BasicMultivariateNormal in _distribution1D:
_distribution1D.BasicMultivariateNormal_swigregister(BasicMultivariateNormal)
class vectord_cxx(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _distribution1D.vectord_cxx_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _distribution1D.vectord_cxx___nonzero__(self)

    def __bool__(self):
        return _distribution1D.vectord_cxx___bool__(self)

    def __len__(self):
        return _distribution1D.vectord_cxx___len__(self)

    def __getslice__(self, i, j):
        return _distribution1D.vectord_cxx___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _distribution1D.vectord_cxx___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _distribution1D.vectord_cxx___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _distribution1D.vectord_cxx___delitem__(self, *args)

    def __getitem__(self, *args):
        return _distribution1D.vectord_cxx___getitem__(self, *args)

    def __setitem__(self, *args):
        return _distribution1D.vectord_cxx___setitem__(self, *args)

    def pop(self):
        return _distribution1D.vectord_cxx_pop(self)

    def append(self, x):
        return _distribution1D.vectord_cxx_append(self, x)

    def empty(self):
        return _distribution1D.vectord_cxx_empty(self)

    def size(self):
        return _distribution1D.vectord_cxx_size(self)

    def swap(self, v):
        return _distribution1D.vectord_cxx_swap(self, v)

    def begin(self):
        return _distribution1D.vectord_cxx_begin(self)

    def end(self):
        return _distribution1D.vectord_cxx_end(self)

    def rbegin(self):
        return _distribution1D.vectord_cxx_rbegin(self)

    def rend(self):
        return _distribution1D.vectord_cxx_rend(self)

    def clear(self):
        return _distribution1D.vectord_cxx_clear(self)

    def get_allocator(self):
        return _distribution1D.vectord_cxx_get_allocator(self)

    def pop_back(self):
        return _distribution1D.vectord_cxx_pop_back(self)

    def erase(self, *args):
        return _distribution1D.vectord_cxx_erase(self, *args)

    def __init__(self, *args):
        _distribution1D.vectord_cxx_swiginit(self, _distribution1D.new_vectord_cxx(*args))

    def push_back(self, x):
        return _distribution1D.vectord_cxx_push_back(self, x)

    def front(self):
        return _distribution1D.vectord_cxx_front(self)

    def back(self):
        return _distribution1D.vectord_cxx_back(self)

    def assign(self, n, x):
        return _distribution1D.vectord_cxx_assign(self, n, x)

    def resize(self, *args):
        return _distribution1D.vectord_cxx_resize(self, *args)

    def insert(self, *args):
        return _distribution1D.vectord_cxx_insert(self, *args)

    def reserve(self, n):
        return _distribution1D.vectord_cxx_reserve(self, n)

    def capacity(self):
        return _distribution1D.vectord_cxx_capacity(self)
    __swig_destroy__ = _distribution1D.delete_vectord_cxx

# Register vectord_cxx in _distribution1D:
_distribution1D.vectord_cxx_swigregister(vectord_cxx)
class vectori_cxx(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _distribution1D.vectori_cxx_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _distribution1D.vectori_cxx___nonzero__(self)

    def __bool__(self):
        return _distribution1D.vectori_cxx___bool__(self)

    def __len__(self):
        return _distribution1D.vectori_cxx___len__(self)

    def __getslice__(self, i, j):
        return _distribution1D.vectori_cxx___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _distribution1D.vectori_cxx___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _distribution1D.vectori_cxx___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _distribution1D.vectori_cxx___delitem__(self, *args)

    def __getitem__(self, *args):
        return _distribution1D.vectori_cxx___getitem__(self, *args)

    def __setitem__(self, *args):
        return _distribution1D.vectori_cxx___setitem__(self, *args)

    def pop(self):
        return _distribution1D.vectori_cxx_pop(self)

    def append(self, x):
        return _distribution1D.vectori_cxx_append(self, x)

    def empty(self):
        return _distribution1D.vectori_cxx_empty(self)

    def size(self):
        return _distribution1D.vectori_cxx_size(self)

    def swap(self, v):
        return _distribution1D.vectori_cxx_swap(self, v)

    def begin(self):
        return _distribution1D.vectori_cxx_begin(self)

    def end(self):
        return _distribution1D.vectori_cxx_end(self)

    def rbegin(self):
        return _distribution1D.vectori_cxx_rbegin(self)

    def rend(self):
        return _distribution1D.vectori_cxx_rend(self)

    def clear(self):
        return _distribution1D.vectori_cxx_clear(self)

    def get_allocator(self):
        return _distribution1D.vectori_cxx_get_allocator(self)

    def pop_back(self):
        return _distribution1D.vectori_cxx_pop_back(self)

    def erase(self, *args):
        return _distribution1D.vectori_cxx_erase(self, *args)

    def __init__(self, *args):
        _distribution1D.vectori_cxx_swiginit(self, _distribution1D.new_vectori_cxx(*args))

    def push_back(self, x):
        return _distribution1D.vectori_cxx_push_back(self, x)

    def front(self):
        return _distribution1D.vectori_cxx_front(self)

    def back(self):
        return _distribution1D.vectori_cxx_back(self)

    def assign(self, n, x):
        return _distribution1D.vectori_cxx_assign(self, n, x)

    def resize(self, *args):
        return _distribution1D.vectori_cxx_resize(self, *args)

    def insert(self, *args):
        return _distribution1D.vectori_cxx_insert(self, *args)

    def reserve(self, n):
        return _distribution1D.vectori_cxx_reserve(self, n)

    def capacity(self):
        return _distribution1D.vectori_cxx_capacity(self)
    __swig_destroy__ = _distribution1D.delete_vectori_cxx

# Register vectori_cxx in _distribution1D:
_distribution1D.vectori_cxx_swigregister(vectori_cxx)

