SCALE Job started on Wed 08/06/2022 20:57:07
With Host name rdfmg
working directory /tmp/scale.khnguy22.7868
and process id 7868.
Input file named /home/khnguy22/RAVEN/raven/tests/framework/CodeInterfaceTests/Scale/SCALE_triton/sampleScale/2/triton_dv1a.inp
and output file named /home/khnguy22/RAVEN/raven/tests/framework/CodeInterfaceTests/Scale/SCALE_triton/sampleScale/2/triton_dv1a.out
##########################################################
***Error: Could not properly parse the input
Potential Free-Form Errors:

line:7 column:1 - Parse Error: expected sequence terminator, found 'end'


Potential Standard Object Notation (SON) Errors:

stream input:4.3: syntax error, unexpected $undefined


***Error: TXSec did not initialize correctly.
***Error: CrossFluxCalculator initialize failed.
