name: Defect Report
description: Report a DEFECT you experienced using the code
title: "[DEFECT] "
labels: defect, priority_normal
body:
  - type: checkboxes
    id: requirements
    attributes:
      label: Thank you for the defect report
      description: Please check the suggestions below before proceeding
      options:
        - label: I am using the latest version of `RAVEN`.
          required: true
        - label: I have read the [Wiki](https://github.com/idaholab/raven/wiki).
          required: true
        - label: |
            I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
            that demonstrates the defect.
  - type: textarea
    id: defect-description
    attributes:
      label: Defect Description
      description: A clear and concise description of what the defect is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the defect.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Screenshots and Input Files
      description: Please attach any additional information like input files, screenshots, recordings and logs, etc.
    validations:
      required: false
  - type: dropdown
    id: which-os
    attributes:
      label: OS
      description: Which OS are you using?
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true
  - type: input
    id: which-version
    attributes:
      label: OS Version
      description: Which OS version are you using?
      placeholder: "10.15.5"
    validations:
      required: false
  - type: dropdown
    id: which-package-manager
    attributes:
      label: Dependency Manager
      description: Which Dependency Manager are you using?
      options:
        - PIP
        - CONDA
    validations:
      required: true
  - type: checkboxes
    id: issue-review
    attributes:
      label: "For Change Control Board: Issue Review"
      description: "This review should occur before any development is performed as a response to this issue."
      options:
        - label: "Is it tagged with a type: defect or task?"
        - label: "Is it tagged with a priority: critical, normal or minor?"
        - label: "If it will impact requirements or requirements tests, is it tagged with requirements?"
        - label: "If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users."
        - label: "Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)"
  - type: checkboxes
    id: issue-closure
    attributes:
      label: "For Change Control Board: Issue Closure"
      description: "This review should occur when the issue is imminently going to be closed."
      options:
        - label: "If the issue is a defect, is the defect fixed?"
        - label: "If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)"
        - label: "If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?"
        - label: "If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?"
        - label: "If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?"
